name: Test Build Only

on:
  workflow_dispatch:
  push:
    tags: ["test-*"]

permissions:
  contents: read

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test Docker build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: rustrocket_x:test

      - name: Success message
        run: echo "✅ Docker build successful! Image built but not pushed." 